#include "waylandsupport.h"
#include "desktopapplications.h"
#include "desktopdatastore.h"
#include "windowmanager.h"
#include <QDebug>
#include <QFile>
#include <QGuiApplication>
#include <QWindow>
#include <QProcess>
#include <QDBusConnection>
#include <QDBusInterface>
#include <QDBusReply>
#include <QDBusMessage>
#include <QDBusVariant>
#include <QJsonDocument>
#include <QJsonObject>
#include <QJsonArray>
#include <QMetaObject>
#include <cstring>

#ifdef HDE_HAVE_WAYLAND
// Generated by wayland-scanner from lib/protocols/wlr-foreign-toplevel-management-unstable-v1.xml
#include "wlr-foreign-toplevel-management-unstable-v1-client-protocol.h"
#endif

namespace {
static WaylandWindow makeDefaultWaylandWindow()
{
    WaylandWindow w;
    // QString members default-construct; initialize PODs explicitly
    w.workspaceIndex = 0;
    w.onAllWorkspaces = false;
    w.isOnCurrentWorkspace = true;
    w.monitorIndex = 0;
    w.x = 0;
    w.y = 0;
    w.width = 0;
    w.height = 0;
    w.visible = true;
    w.focused = false;
    w.minimized = false;
    w.maximized = false;
    w.maximizedHorizontally = false;
    w.maximizedVertically = false;
    w.demandsAttention = false;
    w.urgent = false;
    w.skipTaskbar = false;
    w.skipPager = false;
    w.decorated = true;
    w.resizable = true;
    w.moveable = true;
    w.isWayland = true;
    w.isX11 = false;
    w.pid = 0;
    w.opacity = 1.0;
    w.hasGroup = false;
    w.groupLeaderId = 0;
    w.createdTime = 0;
    w.focusTime = 0;
    w.surface = nullptr;
    w.toplevel = nullptr;
    return w;
}
} // namespace

#ifdef HDE_HAVE_WAYLAND
// Forward declarations so handleRegistryGlobal() can reference the listeners.
extern const zwlr_foreign_toplevel_manager_v1_listener kToplevelManagerListener;
extern const zwlr_foreign_toplevel_handle_v1_listener kToplevelHandleListener;
#endif

WaylandSupport::WaylandSupport(QObject* parent)
    : QObject(parent)
    , m_windowManager(nullptr)
    , m_useWindowManager(true)
    , m_initialized(false)
    , m_display(nullptr)
    , m_ownsDisplay(false)
    , m_registry(nullptr)
    , m_compositor(nullptr)
    , m_xdg_wm_base(nullptr)
    , m_updateTimer(nullptr)
{
    // Try to create a window manager first
    m_windowManager = WindowManagerFactory::createWindowManager(this);
    if (m_windowManager) {
        m_useWindowManager = m_windowManager->initialize();
        if (m_useWindowManager) {
            // Connect window manager signals
            connect(m_windowManager, &WindowManager::windowsUpdated,
                    this, &WaylandSupport::onWindowManagerWindowsUpdated);
            connect(m_windowManager, &WindowManager::windowCreated,
                    this, &WaylandSupport::onWindowManagerWindowCreated);
            connect(m_windowManager, &WindowManager::windowClosed,
                    this, &WaylandSupport::onWindowManagerWindowClosed);
            connect(m_windowManager, &WindowManager::windowActivated,
                    this, &WaylandSupport::onWindowManagerWindowActivated);
            connect(m_windowManager, &WindowManager::workspaceChanged,
                    this, &WaylandSupport::onWindowManagerWorkspaceChanged);
            connect(m_windowManager, &WindowManager::monitorChanged,
                    this, &WaylandSupport::onWindowManagerMonitorChanged);
            
            qDebug() << "WaylandSupport: Using" << m_windowManager->getWindowManagerName() << "window manager";
        } else {
            qDebug() << "WaylandSupport: Window manager initialization failed, falling back to legacy mode";
            delete m_windowManager;
            m_windowManager = nullptr;
            m_useWindowManager = false;
        }
    } else {
        qDebug() << "WaylandSupport: No window manager available, using legacy mode";
        m_useWindowManager = false;
    }
}

WaylandSupport::~WaylandSupport()
{
    // Stop and delete timer first
    if (m_updateTimer) {
        m_updateTimer->stop();
        delete m_updateTimer;
        m_updateTimer = nullptr;
    }

#ifdef HDE_HAVE_WAYLAND
    // Tear down wlroots foreign-toplevel objects first (they depend on wl_display)
    QMutexLocker locker(&m_foreignMutex);
    if (m_displayNotifier) {
        m_displayNotifier->setEnabled(false);
        delete m_displayNotifier;
        m_displayNotifier = nullptr;
    }
    while (!m_foreignToplevels.isEmpty()) {
        auto it = m_foreignToplevels.begin();
        ForeignToplevelData* data = it.value();
        zwlr_foreign_toplevel_handle_v1* handle = it.key();
        m_foreignToplevels.erase(it);
        if (handle) {
            // Client-side proxy destroy (does NOT tell compositor to close the window)
            zwlr_foreign_toplevel_handle_v1_destroy(handle);
        }
        delete data;
    }
    if (m_foreignToplevelManager) {
        zwlr_foreign_toplevel_manager_v1_destroy(m_foreignToplevelManager);
        m_foreignToplevelManager = nullptr;
    }
    if (m_seat) {
        wl_seat_destroy(m_seat);
        m_seat = nullptr;
    }
#endif
    
    // Clean up window manager
    if (m_windowManager) {
        delete m_windowManager;
        m_windowManager = nullptr;
    }
    
    // Clean up Wayland resources
    if (m_xdg_wm_base) {
        // xdg_wm_base_destroy is not available in the current Wayland headers
        // The resource will be cleaned up when the display is disconnected
        m_xdg_wm_base = nullptr;
    }
    if (m_compositor) {
        wl_compositor_destroy(m_compositor);
        m_compositor = nullptr;
    }
    if (m_registry) {
        wl_registry_destroy(m_registry);
        m_registry = nullptr;
    }
    if (m_display && m_ownsDisplay) {
        wl_display_disconnect(m_display);
    }
    m_display = nullptr;
}

bool WaylandSupport::isAvailable()
{
    QString platform = QGuiApplication::platformName();
    QString sessionType = qgetenv("XDG_SESSION_TYPE");
    QString waylandDisplay = qgetenv("WAYLAND_DISPLAY");

    return platform.contains("wayland", Qt::CaseInsensitive)
        || sessionType == "wayland"
        || !waylandDisplay.isEmpty();
}

bool WaylandSupport::initialize()
{
    if (m_initialized)
        return true;

    if (!isAvailable()) {
        qDebug() << "WaylandSupport: Wayland not available";
        return false;
    }

    // Always create our own Wayland connection so all protocol callbacks run
    // in the same Qt thread that dispatches the display fd.
    m_display = wl_display_connect(nullptr);
    if (!m_display) {
        qDebug() << "WaylandSupport: Failed to connect to Wayland display";
        return false;
    }
    m_ownsDisplay = true;

    m_registry = wl_display_get_registry(m_display);
    wl_registry_add_listener(m_registry, &registryListener, this);
    // Mark initialized BEFORE roundtrip so protocol callbacks can populate initial state.
    m_initialized = true;
    wl_display_roundtrip(m_display);

#ifdef HDE_HAVE_WAYLAND
    // If we bound the foreign-toplevel manager during the registry roundtrip,
    // do a second roundtrip to reliably receive the initial list of toplevels.
    // (Many compositors only send existing toplevels after the manager is bound.)
    if (m_foreignToplevelManager) {
        wl_display_roundtrip(m_display);
    }
#endif

#ifdef HDE_HAVE_WAYLAND
    // Hook the Wayland socket into Qt's event loop for live updates.
    if (!m_displayNotifier) {
        const int fd = wl_display_get_fd(m_display);
        if (fd >= 0) {
            m_displayNotifier = new QSocketNotifier(fd, QSocketNotifier::Read, this);
            connect(m_displayNotifier, &QSocketNotifier::activated, this, &WaylandSupport::onWaylandReadable);
            m_displayNotifier->setEnabled(true);
        }
    }
#endif

    // Keep a timer running even for foreign-toplevel to ensure we periodically emit
    // windowsUpdated (and to provide a safety net if compositor doesn't send "done"
    // promptly). This timer does NOT block; it only dispatches pending + emits.
    if (!m_updateTimer) {
        m_updateTimer = new QTimer(this);
        m_updateTimer->setInterval(500);
        connect(m_updateTimer, &QTimer::timeout, this, &WaylandSupport::updateWindows);
    }
    m_updateTimer->start();

    return true;
}

void WaylandSupport::updateWindows()
{
    if (!m_initialized || !m_display)
        return;

    // Only used for legacy polling paths.
    if (m_ownsDisplay) {
        wl_display_dispatch_pending(m_display);
        wl_display_flush(m_display);
    }
    
    // Get all windows and emit signal
    QList<WaylandWindow> windows = getAllWindows();
    static int lastWindowCount = -1;
    if (windows.size() != lastWindowCount) {
        qDebug() << "WaylandSupport: Window count changed from" << lastWindowCount << "to" << windows.size();
        lastWindowCount = windows.size();
        for (const WaylandWindow& window : windows) {
            qDebug() << "  - Window:" << window.title 
                     << "(" << window.appId << ")"
                     << "[WS:" << window.workspaceIndex 
                     << ", Monitor:" << window.monitorIndex
                     << ", " << (window.isWayland ? "Wayland" : "X11")
                     << ", " << (window.focused ? "Focused" : "Unfocused")
                     << "]";
        }
    }
    emit windowsUpdated(windows);
}

#ifdef HDE_HAVE_WAYLAND
void WaylandSupport::onWaylandReadable()
{
    if (!m_initialized || !m_display || !m_displayNotifier) {
        return;
    }
    // Prevent re-entrancy while dispatching
    m_displayNotifier->setEnabled(false);
    wl_display_dispatch(m_display);      // read+dispatch
    wl_display_flush(m_display);
    m_displayNotifier->setEnabled(true);
}
#endif

QList<WaylandWindow> WaylandSupport::getAllWindows()
{
#ifdef HDE_HAVE_WAYLAND
    if (m_foreignToplevelManager) {
        return getWindowsFromForeignToplevel();
    }
#endif
    if (m_useWindowManager && m_windowManager) {
        return m_windowManager->getAllWindows();
    }
    
    // Legacy implementation for backward compatibility
    QList<WaylandWindow> windows;

    if (!m_initialized) {
        qDebug() << "WaylandSupport::getAllWindows() - not initialized";
        return windows;
    }

    // Check if we're running on GNOME (including Unity compatibility mode)
    QString desktop = qgetenv("XDG_CURRENT_DESKTOP").toLower();
    if (desktop.contains("unity") || desktop.contains("gnome")) {
        // Try GNOME Shell D-Bus first (most accurate)
        windows = getWindowsFromGnomeShell();
        if (!windows.isEmpty()) {
            //qDebug() << "WaylandSupport: Using GNOME Shell D-Bus, found" << windows.size() << "windows";
            return windows;
        }
    } else if (desktop.contains("plasma")) {
        // KDE Plasma detected but window management not implemented - return empty list silently
        return windows;
    } else if (desktop.contains("weston")) {
        // Weston detected but window management not implemented - return empty list silently
        return windows;
    } else if (desktop.contains("hypr")) {
        // Hyprland detected but window management not implemented - return empty list silently
        return windows;
    } else if (desktop.contains("river")) {
        // River detected but window management not implemented - return empty list silently
        return windows;
    } else if (desktop.contains("wayfire")) {
        // Wayfire detected but window management not implemented - return empty list silently
        return windows;
    } else if (desktop.contains("labwc")) {
        // Labwc detected but window management not implemented - return empty list silently
        return windows;
    } else {
        // Unknown compositor detected but window management not implemented - return empty list silently
        return windows;
    }

    return windows;
}


QString WaylandSupport::getApplicationIcon(const QString& appId, const QString& wmClass) const
{
    DesktopDataStore* dataStore = DesktopDataStore::instance();
    if (dataStore) {
        // Search for applications by executable name or WM class
        QList<DesktopEntryData> matches = dataStore->searchByExecutable(appId);
        if (matches.isEmpty() && !wmClass.isEmpty()) {
            // Try searching by WM class in the startupWMClass field
            QList<DesktopEntryData> allEntries = dataStore->getAllDesktopEntries();
            foreach (const DesktopEntryData& entry, allEntries) {
                if (entry.startupWMClass == wmClass) {
                    matches.append(entry);
                    break;
                }
            }
        }
        if (!matches.isEmpty()) {
            return matches.first().icon;
        }
    }
    
    // Fallback if DesktopDataStore is not available
    QString fallbackIcon = !appId.isEmpty() ? appId.toLower() : wmClass.toLower();
    return fallbackIcon.isEmpty() ? "application-x-executable" : fallbackIcon;
}

// ---------------- Registry handling ----------------

const wl_registry_listener WaylandSupport::registryListener = {
    [](void* data, wl_registry* registry, uint32_t name, const char* interface, uint32_t version) {
        static_cast<WaylandSupport*>(data)->handleRegistryGlobal(registry, name, interface, version);
    },
    [](void*, wl_registry*, uint32_t) {}
};

void WaylandSupport::handleRegistryGlobal(wl_registry* registry, uint32_t name, const char* interface, uint32_t version)
{
    Q_UNUSED(version);


    // NOTE: We intentionally do NOT bind wl_compositor here.
    // This component only needs foreign-toplevel + seat for taskbar use cases,
    // and binding globals we don't use has caused instability on some setups.
#ifdef HDE_HAVE_WAYLAND
    if (strcmp(interface, "wl_seat") == 0) {
        // Bind the first seat for activation requests.
        if (!m_seat) {
            const uint32_t bindVersion = qMin(version, 5u);
            m_seat = static_cast<wl_seat*>(wl_registry_bind(registry, name, &wl_seat_interface, bindVersion));
        }
    }
#endif
    //else if (strcmp(interface, "xdg_wm_base") == 0) {
    //    m_xdg_wm_base = static_cast<wl_interface*>(
    //        wl_registry_bind(registry, name, &xdg_wm_base_interface, 1));
    //    qDebug() << "WaylandSupport: Got xdg_wm_base";
    //}
    if (strcmp(interface, "zwlr_foreign_toplevel_manager_v1") == 0) {
#ifdef HDE_HAVE_WAYLAND
        if (qEnvironmentVariableIsSet("HDE_DISABLE_FOREIGN_TOPLEVEL")) {
            qDebug() << "WaylandSupport: foreign-toplevel disabled via HDE_DISABLE_FOREIGN_TOPLEVEL";
            return;
        }
        const uint32_t bindVersion = qMin(version, 3u);
        m_foreignToplevelManager = static_cast<zwlr_foreign_toplevel_manager_v1*>(
            wl_registry_bind(registry, name, &zwlr_foreign_toplevel_manager_v1_interface, bindVersion));
        if (m_foreignToplevelManager) {
            zwlr_foreign_toplevel_manager_v1_add_listener(m_foreignToplevelManager, &kToplevelManagerListener, this);
            qDebug() << "WaylandSupport: Bound to zwlr_foreign_toplevel_manager_v1 (version:" << bindVersion << ")";
        }
#else
        Q_UNUSED(registry);
        Q_UNUSED(name);
        Q_UNUSED(interface);
        Q_UNUSED(version);
#endif
    }
}

bool WaylandSupport::activateWindow(void* surface)
{
#ifdef HDE_HAVE_WAYLAND
    if (m_foreignToplevelManager && m_seat && surface) {
        auto* handle = reinterpret_cast<zwlr_foreign_toplevel_handle_v1*>(surface);
        QMutexLocker locker(&m_foreignMutex);
        if (m_foreignToplevels.contains(handle)) {
            zwlr_foreign_toplevel_handle_v1_activate(handle, m_seat);
            if (m_display) wl_display_flush(m_display);
            return true;
        }
    }
#endif
    return false;
}

bool WaylandSupport::closeWindow(void* surface)
{
#ifdef HDE_HAVE_WAYLAND
    if (m_foreignToplevelManager && surface) {
        auto* handle = reinterpret_cast<zwlr_foreign_toplevel_handle_v1*>(surface);
        QMutexLocker locker(&m_foreignMutex);
        if (m_foreignToplevels.contains(handle)) {
            zwlr_foreign_toplevel_handle_v1_close(handle);
            if (m_display) wl_display_flush(m_display);
            return true;
        }
    }
#endif
    return false;
}

void WaylandSupport::scheduleEmitWindowsUpdated()
{
#ifdef HDE_HAVE_WAYLAND
    if (m_emitScheduled) {
        return;
    }
    m_emitScheduled = true;
    QTimer::singleShot(0, this, [this]() {
        m_emitScheduled = false;
        emit windowsUpdated(getWindowsFromForeignToplevel());
    });
#endif
}

QList<WaylandWindow> WaylandSupport::getWindowsFromForeignToplevel() const
{
    QList<WaylandWindow> windows;
#ifdef HDE_HAVE_WAYLAND
    QMutexLocker locker(&m_foreignMutex);
    windows.reserve(m_foreignToplevels.size());
    for (auto it = m_foreignToplevels.begin(); it != m_foreignToplevels.end(); ++it) {
        const ForeignToplevelData* data = it.value();
        if (!data) continue;
        // Don't require "done" or non-empty appId; some compositors can delay those,
        // but taskbars should still show something (title) immediately.
        const QString appIdLower = data->window.appId.toLower();
        if (!appIdLower.isEmpty() && (appIdLower == "desktop" || appIdLower == "background")) continue;
        WaylandWindow w = data->window;
        if (w.clientType.isEmpty()) w.clientType = "Wayland";
        if (w.title.isEmpty()) w.title = w.appId;
        if (w.iconName.isEmpty() && !w.appId.isEmpty()) {
            w.iconName = getApplicationIcon(w.appId, w.wmClass);
        }
        if (w.iconName.isEmpty()) {
            w.iconName = getApplicationIcon(w.appId, w.wmClass);
        }
        windows.append(w);
    }
#endif
    return windows;
}

#ifdef HDE_HAVE_WAYLAND
// ---------------- wlr-foreign-toplevel-manager protocol listeners ----------------
void WaylandSupport::handleToplevelManagerToplevel(void* data, zwlr_foreign_toplevel_manager_v1*, zwlr_foreign_toplevel_handle_v1* toplevel)
{
    WaylandSupport* self = static_cast<WaylandSupport*>(data);
    if (!self || !self->m_initialized || !toplevel) return;

    QMutexLocker locker(&self->m_foreignMutex);
    auto* td = new ForeignToplevelData();
    td->handle = toplevel;
    td->window = makeDefaultWaylandWindow();
    td->window.surface = toplevel;
    td->window.toplevel = toplevel;
    td->done = false;

    zwlr_foreign_toplevel_handle_v1_add_listener(toplevel, &kToplevelHandleListener, self);
    self->m_foreignToplevels[toplevel] = td;
}

void WaylandSupport::handleToplevelManagerFinished(void* data, zwlr_foreign_toplevel_manager_v1*)
{
    WaylandSupport* self = static_cast<WaylandSupport*>(data);
    if (!self) return;
    QMetaObject::invokeMethod(self, [self]() { self->scheduleEmitWindowsUpdated(); }, Qt::QueuedConnection);
}

void WaylandSupport::handleToplevelTitle(void* data, zwlr_foreign_toplevel_handle_v1* toplevel, const char* title)
{
    WaylandSupport* self = static_cast<WaylandSupport*>(data);
    if (!self || !toplevel) return;
    QMutexLocker locker(&self->m_foreignMutex);
    auto* td = self->m_foreignToplevels.value(toplevel, nullptr);
    if (!td) return;
    td->window.title = QString::fromUtf8(title ? title : "");
    if (td->done) {
        QMetaObject::invokeMethod(self, [self]() { self->scheduleEmitWindowsUpdated(); }, Qt::QueuedConnection);
    }
}

void WaylandSupport::handleToplevelAppId(void* data, zwlr_foreign_toplevel_handle_v1* toplevel, const char* app_id)
{
    WaylandSupport* self = static_cast<WaylandSupport*>(data);
    if (!self || !toplevel) return;
    QMutexLocker locker(&self->m_foreignMutex);
    auto* td = self->m_foreignToplevels.value(toplevel, nullptr);
    if (!td) return;
    td->window.appId = QString::fromUtf8(app_id ? app_id : "");
    if (td->done) {
        QMetaObject::invokeMethod(self, [self]() { self->scheduleEmitWindowsUpdated(); }, Qt::QueuedConnection);
    }
}

void WaylandSupport::handleToplevelOutputEnter(void* data, zwlr_foreign_toplevel_handle_v1* toplevel, wl_output*)
{
    WaylandSupport* self = static_cast<WaylandSupport*>(data);
    if (!self || !toplevel) return;
    QMutexLocker locker(&self->m_foreignMutex);
    auto* td = self->m_foreignToplevels.value(toplevel, nullptr);
    if (!td) return;
    td->window.visible = true;
    if (td->done) {
        QMetaObject::invokeMethod(self, [self]() { self->scheduleEmitWindowsUpdated(); }, Qt::QueuedConnection);
    }
}

void WaylandSupport::handleToplevelOutputLeave(void* data, zwlr_foreign_toplevel_handle_v1* toplevel, wl_output*)
{
    WaylandSupport* self = static_cast<WaylandSupport*>(data);
    if (!self || !toplevel) return;
    QMutexLocker locker(&self->m_foreignMutex);
    auto* td = self->m_foreignToplevels.value(toplevel, nullptr);
    if (!td) return;
}

void WaylandSupport::handleToplevelState(void* data, zwlr_foreign_toplevel_handle_v1* toplevel, wl_array* state)
{
    WaylandSupport* self = static_cast<WaylandSupport*>(data);
    if (!self || !toplevel || !state || !state->data) return;
    QMutexLocker locker(&self->m_foreignMutex);
    auto* td = self->m_foreignToplevels.value(toplevel, nullptr);
    if (!td) return;

    td->window.focused = false;
    td->window.minimized = false;
    td->window.maximized = false;
    td->window.visible = true;

    uint32_t* s = static_cast<uint32_t*>(state->data);
    for (size_t i = 0; i < state->size / sizeof(uint32_t); ++i) {
        switch (s[i]) {
            case ZWLR_FOREIGN_TOPLEVEL_HANDLE_V1_STATE_ACTIVATED:
                td->window.focused = true;
                break;
            case ZWLR_FOREIGN_TOPLEVEL_HANDLE_V1_STATE_MINIMIZED:
                td->window.minimized = true;
                td->window.visible = false;
                break;
            case ZWLR_FOREIGN_TOPLEVEL_HANDLE_V1_STATE_MAXIMIZED:
                td->window.maximized = true;
                break;
            default:
                break;
        }
    }
    if (td->done) {
        QMetaObject::invokeMethod(self, [self]() { self->scheduleEmitWindowsUpdated(); }, Qt::QueuedConnection);
    }
}

void WaylandSupport::handleToplevelDone(void* data, zwlr_foreign_toplevel_handle_v1* toplevel)
{
    WaylandSupport* self = static_cast<WaylandSupport*>(data);
    if (!self || !toplevel) return;
    WaylandWindow created;
    bool emitCreated = false;
    {
        QMutexLocker locker(&self->m_foreignMutex);
        auto* td = self->m_foreignToplevels.value(toplevel, nullptr);
        if (!td) return;

        const bool wasDone = td->done;
        td->done = true;

        if (!wasDone && !td->window.appId.isEmpty()) {
            created = td->window;
            emitCreated = true;
        }
    }

    QMetaObject::invokeMethod(self, [self, emitCreated, created]() {
        if (emitCreated) {
            emit self->windowCreated(created);
        }
        self->scheduleEmitWindowsUpdated();
    }, Qt::QueuedConnection);
}

void WaylandSupport::handleToplevelClosed(void* data, zwlr_foreign_toplevel_handle_v1* toplevel)
{
    WaylandSupport* self = static_cast<WaylandSupport*>(data);
    if (!self || !toplevel) return;
    WaylandWindow w;
    {
        QMutexLocker locker(&self->m_foreignMutex);
        auto* td = self->m_foreignToplevels.value(toplevel, nullptr);
        if (!td) return;

        w = td->window;
        self->m_foreignToplevels.remove(toplevel);

        // Destroy client-side proxy now that compositor said it's closed.
        zwlr_foreign_toplevel_handle_v1_destroy(toplevel);
        delete td;
    }

    QMetaObject::invokeMethod(self, [self, w]() {
        emit self->windowClosed(w);
        self->scheduleEmitWindowsUpdated();
    }, Qt::QueuedConnection);
}

void WaylandSupport::handleToplevelParent(void* data, zwlr_foreign_toplevel_handle_v1* toplevel, zwlr_foreign_toplevel_handle_v1*)
{
    WaylandSupport* self = static_cast<WaylandSupport*>(data);
    if (!self || !toplevel) return;
}

const zwlr_foreign_toplevel_manager_v1_listener kToplevelManagerListener = {
    WaylandSupport::handleToplevelManagerToplevel,
    WaylandSupport::handleToplevelManagerFinished
};

const zwlr_foreign_toplevel_handle_v1_listener kToplevelHandleListener = {
    WaylandSupport::handleToplevelTitle,
    WaylandSupport::handleToplevelAppId,
    WaylandSupport::handleToplevelOutputEnter,
    WaylandSupport::handleToplevelOutputLeave,
    WaylandSupport::handleToplevelState,
    WaylandSupport::handleToplevelDone,
    WaylandSupport::handleToplevelClosed,
    WaylandSupport::handleToplevelParent
};
#endif

WaylandWindow WaylandSupport::getWindowInfo(void* surface)
{
    Q_UNUSED(surface);
    WaylandWindow w;
    qDebug() << "WaylandSupport: Getting window info for surface:" << surface;
    return w;
}

bool WaylandSupport::activateWindow(const QString& appId)
{
    if (m_useWindowManager && m_windowManager) {
        return m_windowManager->activateWindow(appId);
    }
    
    // Legacy implementation for backward compatibility
    if (!m_initialized) {
        qDebug() << "WaylandSupport::activateWindow() - not initialized";
        return false;
    }
    
    // Check if we're running on GNOME (including Unity compatibility mode)
    QString desktop = qgetenv("XDG_CURRENT_DESKTOP").toLower();
    if (!desktop.contains("gnome") && !desktop.contains("unity")) {
        qDebug() << "WaylandSupport: Window activation only supported on GNOME/Unity";
        return false;
    }

    // First, try to use the extension's safe ActivateWindow method
    QDBusInterface extensionInterface("org.hdepanel.WindowList",
        "/org/hdepanel/WindowList",
        "org.hdepanel.WindowList",
        QDBusConnection::sessionBus());
    
    if (extensionInterface.isValid()) {
        QDBusReply<bool> reply = extensionInterface.call("ActivateWindow", appId);
        
        if (reply.isValid()) {
            if (reply.value()) {
                qDebug() << "WaylandSupport: Successfully activated window for appId:" << appId;
                return true;
            } else {
                qDebug() << "WaylandSupport: No window found for appId:" << appId;
                return false;
            }
        } else {
            qDebug() << "WaylandSupport: Extension ActivateWindow call failed:" << reply.error().message();
            // Fall through to unsafe method
        }
    } else {
        qDebug() << "WaylandSupport: Extension not available for window activation, falling back to unsafe mode";
        // Fall through to unsafe method
    }

    // Fallback: use unsafe mode (requires extra permissions)
    QDBusInterface shellInterface("org.gnome.Shell",
        "/org/gnome/Shell",
        "org.gnome.Shell",
        QDBusConnection::sessionBus());

    // First, enable unsafe mode
    QDBusMessage unsafeMessage = shellInterface.call("Eval", "global.context.unsafe_mode = true");
    if (unsafeMessage.type() != QDBusMessage::ReplyMessage || unsafeMessage.arguments().size() < 2) {
        qDebug() << "WaylandSupport: Failed to enable unsafe mode for window activation";
        return false;
    }
    bool unsafeSuccess = unsafeMessage.arguments()[0].toBool();
    if (!unsafeSuccess) {
        qDebug() << "WaylandSupport: Unsafe mode not enabled for window activation";
        qDebug() << "WaylandSupport: Please install the HDEPanel extension from gnome-extension/hdepanel-window-list@hdepanel";
        return false;
    }

    // Find and activate the window with the given appId
    QString jsCode = QString(R"(
        (function() {
            const windows = global.get_window_actors()
                .filter(w => w.meta_window && w.meta_window.get_title)
                .map(w => {
                    const mw = w.meta_window;
                    const title = mw.get_title() || '';
                    const appId = mw.get_gtk_application_id() || mw.get_wm_class() || '';
                    const wmClass = mw.get_wm_class() || '';
                    const windowType = mw.get_window_type();
                    
                    // Filter out panels and system services
                    const appIdLower = appId.toLowerCase();
                    const wmClassLower = wmClass.toLowerCase();
                    const isPanel = appIdLower.includes('hdepanel') || 
                                    wmClassLower.includes('hdepanel') ||
                                    appIdLower.includes('hde/panel') || 
                                    wmClassLower.includes('hde/panel') ||
                                    appIdLower === 'hde/panel' ||
                                    wmClassLower === 'hde/panel';
                    
                    // Filter out system services and utilities
                    const isSystemService = appIdLower.includes('org.kde.xwaylandvideobridge') ||
                                           appIdLower.includes('org.kde.plasma') ||
                                           appIdLower.includes('org.gnome.shell') ||
                                           appIdLower.includes('com.canonical.unity') ||
                                           appIdLower.includes('com.ubuntu.') ||
                                           appIdLower.includes('org.freedesktop.') ||
                                           appIdLower.startsWith('gjs') ||
                                           appIdLower.startsWith('gnome-shell') ||
                                           wmClassLower.includes('xwaylandvideobridge') ||
                                           wmClassLower.includes('plasma') ||
                                           wmClassLower.includes('gnome-shell');
                    
                    return {
                        title: title,
                        app_id: appId,
                        wm_class: wmClass,
                        window_type: windowType,
                        visible: !mw.minimized,
                        focused: mw.has_focus(),
                        is_wayland: mw.get_client_type() === 1,
                        is_panel: isPanel,
                        is_system_service: isSystemService,
                        meta_window: mw,
                        window_actor: w
                    };
                })
                .filter(w => !w.is_panel && !w.is_system_service && w.visible && w.window_type === 0);
            
            // Find the window with matching appId
            const targetWindow = windows.find(w => 
                w.app_id === '%1' || w.wm_class === '%1'
            );
            
            if (targetWindow) {
                // Activate the window
                targetWindow.meta_window.activate(global.get_current_time());
                return true;
            } else {
                return false;
            }
        })()
    )").arg(appId);

    QDBusMessage message = shellInterface.call("Eval", jsCode);
    
    if (message.type() == QDBusMessage::ReplyMessage && message.arguments().size() >= 2) {
        bool success = message.arguments()[0].toBool();
        QString result = message.arguments()[1].toString();
        
        if (success) {
            bool activated = result.toLower() == "true";
            if (activated) {
                qDebug() << "WaylandSupport: Successfully activated window for appId:" << appId;
                return true;
            } else {
                qDebug() << "WaylandSupport: No window found for appId:" << appId;
                return false;
            }
        } else {
            qDebug() << "WaylandSupport: JavaScript execution failed for window activation:" << result;
            return false;
        }
    } else {
        qDebug() << "WaylandSupport: D-Bus call failed for window activation:" << message.errorMessage();
        return false;
    }
}

bool WaylandSupport::closeWindow(const QString& appId)
{
    if (m_useWindowManager && m_windowManager) {
        return m_windowManager->closeWindow(appId);
    }
    
    // Legacy implementation for backward compatibility
    if (!m_initialized) {
        qDebug() << "WaylandSupport::closeWindow() - not initialized";
        return false;
    }
    
    // Check if we're running on GNOME (including Unity compatibility mode)
    QString desktop = qgetenv("XDG_CURRENT_DESKTOP").toLower();
    if (!desktop.contains("gnome") && !desktop.contains("unity")) {
        qDebug() << "WaylandSupport: Window closing only supported on GNOME/Unity";
        return false;
    }

    // Try to use the extension's safe CloseWindow method
    QDBusInterface extensionInterface("org.hdepanel.WindowList",
        "/org/hdepanel/WindowList",
        "org.hdepanel.WindowList",
        QDBusConnection::sessionBus());
    
    if (extensionInterface.isValid()) {
        QDBusReply<bool> reply = extensionInterface.call("CloseWindow", appId);
        
        if (reply.isValid()) {
            if (reply.value()) {
                qDebug() << "WaylandSupport: Successfully closed window for appId:" << appId;
                return true;
            } else {
                qDebug() << "WaylandSupport: No window found to close for appId:" << appId;
                return false;
            }
        } else {
            qDebug() << "WaylandSupport: Extension CloseWindow call failed:" << reply.error().message();
            return false;
        }
    } else {
        qDebug() << "WaylandSupport: Extension not available for window closing";
        return false;
    }
}

bool WaylandSupport::minimizeWindow(const QString& appId)
{
    if (m_useWindowManager && m_windowManager) {
        return m_windowManager->minimizeWindow(appId);
    }
    return false; // Not implemented in legacy mode
}

bool WaylandSupport::maximizeWindow(const QString& appId)
{
    if (m_useWindowManager && m_windowManager) {
        return m_windowManager->maximizeWindow(appId);
    }
    return false; // Not implemented in legacy mode
}

bool WaylandSupport::unmaximizeWindow(const QString& appId)
{
    if (m_useWindowManager && m_windowManager) {
        return m_windowManager->unmaximizeWindow(appId);
    }
    return false; // Not implemented in legacy mode
}

bool WaylandSupport::moveWindowToWorkspace(const QString& appId, int workspace)
{
    if (m_useWindowManager && m_windowManager) {
        return m_windowManager->moveWindowToWorkspace(appId, workspace);
    }
    return false; // Not implemented in legacy mode
}

bool WaylandSupport::moveWindowToMonitor(const QString& appId, int monitor)
{
    if (m_useWindowManager && m_windowManager) {
        return m_windowManager->moveWindowToMonitor(appId, monitor);
    }
    return false; // Not implemented in legacy mode
}

// Window manager information methods
QString WaylandSupport::getWindowManagerName() const
{
    if (m_useWindowManager && m_windowManager) {
        return m_windowManager->getWindowManagerName();
    }
    return "Legacy Wayland Support";
}

WindowManager::Type WaylandSupport::getWindowManagerType() const
{
    if (m_useWindowManager && m_windowManager) {
        return m_windowManager->getType();
    }
    return WindowManager::Type::Unknown;
}

QString WaylandSupport::getWindowManagerVersion() const
{
    if (m_useWindowManager && m_windowManager) {
        return m_windowManager->getVersion();
    }
    return "Unknown";
}

bool WaylandSupport::supportsWorkspaces() const
{
    if (m_useWindowManager && m_windowManager) {
        return m_windowManager->supportsWorkspaces();
    }
    return false;
}

bool WaylandSupport::supportsMultipleMonitors() const
{
    if (m_useWindowManager && m_windowManager) {
        return m_windowManager->supportsMultipleMonitors();
    }
    return false;
}

int WaylandSupport::getCurrentWorkspace() const
{
    if (m_useWindowManager && m_windowManager) {
        return m_windowManager->getCurrentWorkspace();
    }
    return 0;
}

int WaylandSupport::getWorkspaceCount() const
{
    if (m_useWindowManager && m_windowManager) {
        return m_windowManager->getWorkspaceCount();
    }
    return 1;
}

QStringList WaylandSupport::getWorkspaceNames() const
{
    if (m_useWindowManager && m_windowManager) {
        return m_windowManager->getWorkspaceNames();
    }
    return QStringList() << "Workspace 1";
}

int WaylandSupport::getMonitorCount() const
{
    if (m_useWindowManager && m_windowManager) {
        return m_windowManager->getMonitorCount();
    }
    return 1;
}

QStringList WaylandSupport::getMonitorNames() const
{
    if (m_useWindowManager && m_windowManager) {
        return m_windowManager->getMonitorNames();
    }
    return QStringList() << "Monitor 1";
}

// Signal handlers for window manager events
void WaylandSupport::onWindowManagerWindowsUpdated(const QList<WaylandWindow>& windows)
{
    emit windowsUpdated(windows);
}

void WaylandSupport::onWindowManagerWindowCreated(const WaylandWindow& window)
{
    emit windowCreated(window);
}

void WaylandSupport::onWindowManagerWindowClosed(const WaylandWindow& window)
{
    emit windowClosed(window);
}

void WaylandSupport::onWindowManagerWindowActivated(const WaylandWindow& window)
{
    emit windowActivated(window);
}

void WaylandSupport::onWindowManagerWorkspaceChanged(int workspace)
{
    emit workspaceChanged(workspace);
}

void WaylandSupport::onWindowManagerMonitorChanged(int monitor)
{
    emit monitorChanged(monitor);
}

QList<WaylandWindow> WaylandSupport::getWindowsFromExtension()
{
    QList<WaylandWindow> windows;
    
    // Try to call our GNOME Shell extension
    QDBusInterface iface("org.gnome.Shell",
                         "/org/hdepanel/WindowList",
                         "org.hdepanel.WindowList",
                         QDBusConnection::sessionBus());
    
    if (!iface.isValid()) {
        // Extension not installed or not enabled
        return windows;
    }
    
    QDBusReply<QString> reply = iface.call("GetWindows");
    
    if (!reply.isValid()) {
        qDebug() << "WaylandSupport: HDEPanel extension call failed:" << reply.error().message();
        return windows;
    }
    
    QString jsonData = reply.value();
    if (jsonData.isEmpty()) {
        return windows;
    }
    
    // Parse JSON array
    QJsonParseError error;
    QJsonDocument doc = QJsonDocument::fromJson(jsonData.toUtf8(), &error);
    
    if (error.error != QJsonParseError::NoError) {
        qDebug() << "WaylandSupport: JSON parse error:" << error.errorString();
        return windows;
    }
    
    if (!doc.isArray()) {
        qDebug() << "WaylandSupport: Expected JSON array";
        return windows;
    }
    
    QJsonArray windowsArray = doc.array();
    
    for (const QJsonValue& value : windowsArray) {
        if (!value.isObject()) {
            continue;
        }
        
        QJsonObject obj = value.toObject();
        QString title = obj["title"].toString();
        QString appId = obj["app_id"].toString();
        QString wmClass = obj["wm_class"].toString();
        
        if (title.isEmpty()) {
            continue;
        }
        
        WaylandWindow window;
        
        // Basic identification
        window.title = title;
        window.appId = appId;
        window.wmClass = wmClass;
        window.wmInstanceClass = obj["wm_instance_class"].toString();
        window.role = obj["role"].toString();
        
        // Workspace/Desktop information
        window.workspaceIndex = obj["workspace_index"].toInt();
        window.workspaceName = obj["workspace_name"].toString();
        window.onAllWorkspaces = obj["on_all_workspaces"].toBool();
        window.isOnCurrentWorkspace = obj["is_on_current_workspace"].toBool();
        
        // Screen/Monitor information
        window.monitorIndex = obj["monitor_index"].toInt();
        
        // Geometry
        window.x = obj["x"].toInt();
        window.y = obj["y"].toInt();
        window.width = obj["width"].toInt();
        window.height = obj["height"].toInt();
        
        // Window state
        window.visible = obj["visible"].toBool();
        window.focused = obj["focused"].toBool();
        window.minimized = obj["minimized"].toBool();
        window.maximized = obj["maximized"].toBool();
        window.maximizedHorizontally = obj["maximized_horizontally"].toBool();
        window.maximizedVertically = obj["maximized_vertically"].toBool();
        
        // Window flags
        window.demandsAttention = obj["demands_attention"].toBool();
        window.urgent = obj["urgent"].toBool();
        window.skipTaskbar = obj["skip_taskbar"].toBool();
        window.skipPager = obj["skip_pager"].toBool();
        window.decorated = obj["decorated"].toBool();
        window.resizable = obj["resizable"].toBool();
        window.moveable = obj["moveable"].toBool();
        
        // Client type
        window.isWayland = obj["is_wayland"].toBool();
        window.isX11 = obj["is_x11"].toBool();
        window.clientType = obj["client_type"].toString();
        
        // Process information
        window.pid = obj["pid"].toInt();
        window.sandboxedAppId = obj["sandboxed_app_id"].toString();
        
        // Visual properties
        window.opacity = obj["opacity"].toDouble();
        
        // Group information
        window.hasGroup = obj["has_group"].toBool();
        window.groupLeaderId = obj["group_leader_id"].toVariant().toULongLong();
        
        // Timestamps
        window.createdTime = obj["created_time"].toVariant().toULongLong();
        window.focusTime = obj["focus_time"].toVariant().toULongLong();
        
        // Legacy fields for compatibility
        window.surface = reinterpret_cast<void*>(
            static_cast<quintptr>(obj["id"].toVariant().toULongLong()));
        window.toplevel = nullptr;
        
        // Try to find icon using both app_id and wm_class
        window.iconName = getApplicationIcon(appId, wmClass);
        
        windows.append(window);
    }
    
    return windows;
}

QList<WaylandWindow> WaylandSupport::getWindowsFromGnomeShell()
{
    QList<WaylandWindow> windows;
    
    // First, try to use our extension (safe method)
    windows = getWindowsFromExtension();
    
    // If extension returned results, use them
    if (!windows.isEmpty()) {
        return windows;
    }
    
    // Otherwise, fall back to unsafe eval method
    static bool warnedAboutUnsafeMode = false;
    if (!warnedAboutUnsafeMode) {
        qDebug() << "WaylandSupport: HDEPanel extension not found, falling back to unsafe mode";
        qDebug() << "WaylandSupport: Install the extension from gnome-extension/hdepanel-window-list@hdepanel";
        warnedAboutUnsafeMode = true;
    }
    
    // Check if we're running on GNOME (including Unity compatibility mode)
    QString desktop = qgetenv("XDG_CURRENT_DESKTOP").toLower();
    if (!desktop.contains("gnome") && !desktop.contains("unity")) {
        qDebug() << "WaylandSupport: Not running on GNOME/Unity, desktop:" << desktop;
        return windows;
    }

    QDBusInterface interface("org.gnome.Shell",
        "/org/gnome/Shell",
        "org.gnome.Shell",
        QDBusConnection::sessionBus());

    // First, enable unsafe mode
    QDBusMessage unsafeMessage = interface.call("Eval", "global.context.unsafe_mode = true");
    if (unsafeMessage.type() != QDBusMessage::ReplyMessage || unsafeMessage.arguments().size() < 2) {
        qDebug() << "WaylandSupport: Failed to enable unsafe mode:" << unsafeMessage.errorMessage();
        return windows;
    }
    bool unsafeSuccess = unsafeMessage.arguments()[0].toBool();
    QString unsafeResult = unsafeMessage.arguments()[1].toString();
    if (!unsafeSuccess) {
        qDebug() << "WaylandSupport: Unsafe mode not enabled";
        return windows;
    }

    // Get window information using get_window_actors
    // This gets both Wayland native and XWayland (X11) windows
    QDBusMessage message = interface.call(
        "Eval",
        R"(
            global.get_window_actors()
                .filter(w => w.meta_window && w.meta_window.get_title)
                .map(w => {
                    const mw = w.meta_window;
                    const title = mw.get_title() || '';
                    const appId = mw.get_gtk_application_id() || mw.get_wm_class() || '';
                    const wmClass = mw.get_wm_class() || '';
                    const windowType = mw.get_window_type();
                    
                    // Filter out hdepanel and system services - only check app_id/wm_class, not title
                    // (title can contain "hdepanel" if editing hdepanel project files)
                    const appIdLower = appId.toLowerCase();
                    const wmClassLower = wmClass.toLowerCase();
                    const isPanel = appIdLower.includes('hdepanel') || 
                                    wmClassLower.includes('hdepanel') ||
                                    appIdLower.includes('hde/panel') || 
                                    wmClassLower.includes('hde/panel') ||
                                    appIdLower === 'hde/panel' ||
                                    wmClassLower === 'hde/panel';
                    
                    // Filter out system services and utilities
                    const isSystemService = appIdLower.includes('org.kde.xwaylandvideobridge') ||
                                           appIdLower.includes('org.kde.plasma') ||
                                           appIdLower.includes('org.gnome.shell') ||
                                           appIdLower.includes('com.canonical.unity') ||
                                           appIdLower.includes('com.ubuntu.') ||
                                           appIdLower.includes('org.freedesktop.') ||
                                           appIdLower.startsWith('gjs') ||
                                           appIdLower.startsWith('gnome-shell') ||
                                           wmClassLower.includes('xwaylandvideobridge') ||
                                           wmClassLower.includes('plasma') ||
                                           wmClassLower.includes('gnome-shell');
                    
                    return {
                        title: title,
                        id: mw.get_id(),
                        app_id: appId,
                        wm_class: wmClass,
                        window_type: windowType,
                        visible: !mw.minimized,
                        focused: mw.has_focus(),
                        is_wayland: mw.get_client_type() === 1, // 1=Wayland, 0=X11
                        is_panel: isPanel,
                        is_system_service: isSystemService,
                        surface: mw.get_id().toString()
                    };
                })
                .map(JSON.stringify)
                .join('\n')
        )"
    );

    if (message.type() == QDBusMessage::ReplyMessage && message.arguments().size() >= 2) {
        bool success = message.arguments()[0].toBool();
        QString jsResult = message.arguments()[1].toString();
            
            if (success && !jsResult.isEmpty()) {
                //qDebug() << "WaylandSupport: GNOME Shell returned:" << jsResult;
                
                // The result is a JSON string containing escaped JSON objects
                QString decodedJson = jsResult;
                
                // Remove outer quotes if present
                if (decodedJson.startsWith("\"") && decodedJson.endsWith("\"")) {
                    decodedJson = decodedJson.mid(1, decodedJson.length() - 2);
                }
                
                // Decode escaped sequences
                decodedJson.replace("\\n", "\n");
                decodedJson.replace("\\\"", "\"");
                decodedJson.replace("\\\\", "\\");
                
                // Split into individual JSON objects
                QStringList lines = decodedJson.split('\n', Qt::SkipEmptyParts);
                
                for (const QString& line : lines) {
                    QJsonParseError lineError;
                    QJsonDocument doc = QJsonDocument::fromJson(line.toUtf8(), &lineError);
                    if (lineError.error != QJsonParseError::NoError) {
                        continue;
                    }
                
                    QJsonObject obj = doc.object();
                    QString title = obj["title"].toString();
                    QString appId = obj["app_id"].toString();
                    QString wmClass = obj["wm_class"].toString();
                    int windowType = obj["window_type"].toInt();
                    bool visible = obj["visible"].toBool();
                    bool focused = obj["focused"].toBool();
                    bool isWayland = obj["is_wayland"].toBool();
                    bool isPanel = obj["is_panel"].toBool();
                    bool isSystemService = obj["is_system_service"].toBool();
                    
                    // Only add non-panel, non-system-service, visible, normal windows with titles
                    // window_type 0 = NORMAL, 1 = DIALOG, 2 = MODAL_DIALOG, etc.
                    if (!isPanel && !isSystemService && !title.isEmpty() && visible && windowType == 0) {
                        WaylandWindow window;
                        window.title = title;
                        window.appId = appId;
                        window.visible = visible;
                        window.focused = focused;
                        window.surface = reinterpret_cast<void*>(
                            static_cast<quintptr>(obj["id"].toVariant().toULongLong()));
                        
                        // Try to find icon using both app_id and wm_class
                        window.iconName = getApplicationIcon(appId, wmClass);
                        
                        windows.append(window);
                        /*
                        qDebug() << "WaylandSupport: Found window:" << title
                                 << "(" << (appId.isEmpty() ? wmClass : appId) << ")"
                                 << "[" << (isWayland ? "Wayland" : "X11") << "]";
                        */
                    }
                }
            } else {
                qDebug() << "WaylandSupport: JavaScript execution failed or empty result:" << jsResult;
            }
    } else {
        qDebug() << "WaylandSupport: D-Bus call failed:" << message.errorMessage();
    }
    
    return windows;
}
